---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: helloworlds.interview.swarz.com
spec:
  group: interview.swarz.com
  names:
    kind: HelloWorld
    listKind: HelloWorldList
    plural: helloworlds
    singular: helloworld
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: HelloWorld is the Schema for the helloworlds API
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            description: HelloWorldSpec defines the desired state of HelloWorld
            properties:
              name:
                description: String if the name or message to which Hello will be
                  prepended.
                type: string
            type: object
          status:
            description: HelloWorldStatus defines the observed state of HelloWorld
            properties:
              message:
                description: Message is the result of the controller work
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}

