apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-operator
  namespace: {{ .Release.Namespace }}
  labels:
{{ toYaml .Values.labels | indent 4 }}   
spec:
  selector:
    matchLabels:
{{ toYaml .Values.labels | indent 6 }}
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: operator
      labels:
{{ toYaml .Values.labels | indent 8 }}
    spec:
      containers:
      - image: {{ index .Values.image }}
        name: operator
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: helloworld-operator
      terminationGracePeriodSeconds: 10
